### ISSUE TITLE
[BUG] Instapassed textures doesn't get pushed to GitHub

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Discord-Bot#136]
**Describe the bug**
When using the star emoji to instapass the texture, the texture is sent to #results but nothing happens after

**To Reproduce**
1. React any textures anywhere in submissions channels with the star emote
2. See #results
3. Nothing

**Expected behavior**
Push to GitHub + Contribution added to the database.

**Additional context**
I haven't coded anything for that yet (oofed).

**Comment by Juknum** [comment]
This doesn't mean that textures are added to github & database, that's why I've reported that issue, close it again if texture are pushed to github & contribution created in the database

**Comment by RobertRR11** [comment]
The instapassing was just an issue of not being updated to discord.js v13, which is fixed now. And I'm sure it has worked before, then why shouldn't it work if the actual issue is fixed?

**Comment by Juknum** [comment]
Because the downloading texture & contributions creation process are made to only keep the :upvote: emojis, not the :instapass: one :/
That's only that, but I wanted to make it directly pushed + contribution created rather than waiting for the daily push

**Comment by RobertRR11** [comment]
Actually, the bot looks for instapassed textures
![image](https://user-images.githubusercontent.com/57044042/133318274-a1271e7f-ba25-492b-9301-ea3f62e4c6e2.png)
but for some reason the instapassed texture https://discord.com/channels/747574286356840609/797648495804678154/887032206466351125 didn't get pushed anyway
at least this should be fixed before we have a massive amount of unpushed textures _again_

**Comment by RobertRR11** [comment]
fixed in 725b1e0 and 6f35be2

**Comment by 3vorp** [comment]
fixed with #229  (probably), gonna close it now
