### ISSUE TITLE
[REQUEST] Show contributor name instead of mention if contributor is not in the server

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Discord-Bot#159]
When the bot tries to get the contributor when (for example) displaying the output of the /texture command, but the contributor is not in the server the command is executed in, only the user ID gets displayed, which is not helpful at all. (this is supposed to be Hozz.)
![Snímek obrazovky 2021-12-30 v 12 40 02](https://user-images.githubusercontent.com/59484948/147748764-e7285d89-b463-4ce8-9d5b-f6a573807f6b.png)
It would be really nice if, instead of this, the bot could check whether a given contributor is in the server, and if they're not, display the contributor's name instead. A less clean workaround would be to do something like [contributor mention] (contributor name) for every contributor, skipping the server check.

**Comment by TheRolfFR** [comment]
Sometimes this happen on the same server, but you never met this person yet on a text channel, As a result the username is not loaded. But yes, we should replace it with a string.

**Comment by Pomi108** [comment]
This doesn't seem to work anymore…
![Snímek obrazovky 2022-02-28 v 19 40 42](https://user-images.githubusercontent.com/59484948/156039611-d33f0ce0-b422-4f56-9c9d-6262a701a65e.png)
(here you can see that Cituation is being pinged – you can only see the name because i've got him in my cache, though.)

**Comment by Juknum** [comment]
It's perfectly normal as it hasn't been implemented yet in the TS version

**Comment by Pomi108** [comment]
Ah okay then
