### ISSUE TITLE
[REQUEST] Add a configurable starboard

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/Discord-Bot#176]
yeah

**Comment by Juknum** [comment]
starboard?

**Comment by RobertRR11** [comment]
> starboard?

![image](https://user-images.githubusercontent.com/57044042/161402975-83296c67-749b-4dfc-9067-f2f97c303408.png)

**Comment by Juknum** [comment]
Why not, It's like a "generic pin channel"? Btw bot messages can't be published in announcement channels

**Comment by RobertRR11** [comment]
> Why not, It's like a "generic pin channel"?
It's not a pin channel, it is for showing stuff that has gotten a specific amount of star reactions

> Btw bot messages can't be published in announcement channels
I haven't even talked about that?

**Comment by Juknum** [comment]
> I haven't even talked about that?
I know xd, but your screen showed an announcement channel

> It's not a pin channel, it is for showing stuff that has gotten a specific amount of star reactions
Ok 👍

**Comment by Pomi108** [comment]
Is this still necessary seeing as we have Wynem now?

**Comment by RobertRR11** [comment]
nope
