### ISSUE TITLE
[Bug] Bot is demultiplied when restarted using `/restart`

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Discord-Bot#179]
### What happened?

When using `/restart` to restart the bot, the bot is actually restarted without being correctly killed first, leading to an infinite loop of errors such as: `DiscordAPIError: Interaction has already been acknowledged` because the bot is trying to respond to interactions for each instance of itself (but it works 1 time only)

### To reproduce

1. Be a developer and do `/restart`
2. The bot restart, yeet
3. Do `/ping`
4. Observes the `DiscordAPIError: Interaction has already been acknowledged` error loop

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49886317/163067076-55080d93-a795-48ae-84d8-48366c8326e8.png)
![image](https://user-images.githubusercontent.com/49886317/163067088-594baa92-7fa7-4cff-b997-4d2bc4fae786.png)

### Notes

- This might be related to [this line](https://github.com/Faithful-Resource-Pack/Discord-Bot/blob/typescript/src/client/client.ts#L93) of code which is weird because the destroy object instantiates itself again and again
- I put the security flag on it since it could lead to API spam which could lead to the bot being banned from using the API? (Maybe idk)

**Comment by Juknum** [comment]
Did you fix it in your commit? @nick-1666
Have you committed? xd

**Comment by nick-1666** [comment]
It was completely fixed but I was making wierd functions and variables and it all can be done much better

**Comment by nick-1666** [comment]
is this not fixed by my commit @Juknum

**Comment by Juknum** [comment]
Can't reproduce in v2.4.0 (seems to be fixed)
