### ISSUE TITLE
[Feature] Submission System v3 (TS Bot)

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Discord-Bot#193]
> This issue is to keep track of what's needs to be done before releasing the submission system v3

### "Frontend" part
- [x] Create a special event that runs when a user is sending a message inside a submit channel
  - [x] Set up submission channels inside a global config file for both discord & teams (groups of discord servers)
- [x] Create an automated function that checks for submission
  - [x] Submission should be stored on the bot & saved into a `.json` file on any changes
### "Backend" part
- [x] When a submission is over (and successfully ended), the file should be:
  - [x] Create a contribution to the API
    - [x] all API endpoints should be written
    - [x] ALL the current contribution system should be converted to the new format
  - [x] Downloaded on the local git repo
  - [x] Pushed to each branch the texture exists with a commit that contains the information:
    - [x] Contributors
    - [x] Texture name

## Features 
- [x] No more daily push, everything is doing synchronously per texture; this will allow us to:
  - [x] Also specify contributors in the submission git commit
  - [x] Being able to reverse a git commit that wrongly comes up to the pack
- [x] The user is able to submit a `.zip` with multiple textures
- [ ] The user is able to submit `.tga` (MCBE) files
- [x] A compared version of the textures is shown inside the submission embed
  - [x] The compared version should be animated when the texture is registered as being animated
- [x] Votes are anonymous
  - [ ] They can only be seen by:
    - [x] the submitter (of course)
    - [x] #202
    - [ ] council members
    - [ ] admins
- [ ] Contributors can be listed without being mentioned (only writing their names should work) 
  - #168 
  - #159 
- [x] Submission now clearly shows their status within a specific colour for the embed
  - yellow: instapassed
  - green: added to the pack
  - red: invalidated
  - black: not added to the pack
  - crimson: in council
- [x] Timed events should be configurable:
  - [x] Should be in the config JSON
  - [x] Time before the council is customizable (default 3 days)
  - [x] Time before pushed is customizable (in council phase/default 1 day)
  - [x] Council can be skipped / disabled
- [x] Contributor role is automatically added to the user if the contribution succeeds (instapassed/added)
- [ ] Matching default resources should be displayed (programmer art when the pack is progart OR jappa otherwise)

**Comment by nick-1666** [comment]
black and red should switch imo. My reasoning is as follows:

green and red is unanimously understood as yes and no and black is more severe than red

**Comment by Juknum** [comment]
red is for invalid, black is for something that passed out (somewhat died)

**Comment by Pomi108** [comment]
The bot should also losslessly compress every texture before pushing it to the repositories

**Comment by 3vorp** [comment]
also might be nice that when a texture gets pushed the description in the discord message gets put as the description of the commit (so that if it's a bugfix/a major change people on the github know that more easily) now that each texture is pushed separately

oh yeah also I agree with nick about switching the invalid and failed colors, failed should be red since that's the color of the downvote button/symbol and black is more serious.

**Comment by Pomi108** [comment]
Paired with [App#81](https://github.com/Faithful-Resource-Pack/App/issues/81):

When submitting a texture, the bot should look what projects the texture is featured in, display that in the embed, and, when pushing, it should push it to the appropriate repositories for all projects.

The project the texture is used in should also be displayed in embeds of commands such as `/texture`.

**Comment by Pomi108** [comment]
Once a texture passes voting, the authors of this texture should also be given the Contributor role unless they have it already

**Comment by 3vorp** [comment]
> Contributors can be listed without being mentioned (only writing their names should work)

This might be weird if multiple users in the server have similar names, I'd suggest using Discord IDs in addition to pings in case you don't want to bother the co-author. Would also be helpful if the user is no longer in the server like Lethal or Cituation.

**Comment by 3vorp** [comment]
Also a bug I've noticed, Managers and Council members cannot currently speak in voting channels like they can on the old submission system, which is very useful for short announcements, instapass/invalid reasonings, etc

**Comment by 3vorp** [comment]
More of a feature, but if a texture is being replaced when submitted, show the current one in the comparison image next to the new one, so people don't have to search it up to see if the new texture is an improvement or not.

**Comment by Pomi108** [comment]
Just noticed, the v3 submissions don't display the file paths in the submission embed. Please re-add that, it's very useful for me

**Comment by Juknum** [comment]
> Just noticed, the v3 submissions don't display the file paths in the submission embed. Please re-add that, it's very useful for me

It's useful, but it takes a lot of space, space which can increase in the future. The best compromise would be a link to the webapp where all paths are there

**Comment by 3vorp** [comment]
I'd remove the tags in favor of the filepaths tbh, tags are just a watered-down version of the filepaths anyways and are way less useful

**Comment by Pomi108** [comment]
agreed

**Comment by 3vorp** [comment]
In light of recent events, I think it's safe to say that v3 submissions have been abandoned and will likely not be continued. However, many of the proposed changes have found their way into the current submission system in some form since the creation of this comment, so I'm going to close it for now.
