### ISSUE TITLE
[Bug] /todo command still doesn't have remove function

### ISSUE THREAD

**Issue by apicella1** [Faithful-Resource-Pack/Discord-Bot#201]
### What happened?

The command, `/todo add` was added a few months ago. It was meant to be a replacement for the todo list currently stored in a Google doc. Council can add things to that list, but we have no way of removing them. 

### To reproduce

Do /todo add
There's no command to remove the items from the todo list.

**Comment by 3vorp** [comment]
since /todo is kinda defunct and has been largely removed from the bot, I'm just gonna close it for now
