### ISSUE TITLE
co-authors

### ISSUE THREAD

**Issue by nick-1666** [Faithful-Resource-Pack/Discord-Bot#202]

**Comment by nick-1666** [comment]
I have pondered on this specific issue. Currently we use the userid in the embed and fetch it later so we can maintain ownership over it. Storing multiple user ids is inefficient and unreasonable seeing as textures can get an uncapped size of co-authors. First i thought of Hexadecimal but it would still be too long, then i tried Base 32 and 64 which both will be unreadable and more of an eyesore than a simple number. Then i realised we could store a json file for submissions which gets cleaned once the submission is up (i.e it gets passed or invalidated or rejected ect). We can have key value pairs where the key is stored on the footer of the embed and the value is an array of signed int 64s. This way we cover all discord ids and leave it to look decently nice. To accommodate older posts and new submissions with only one author, our keys can start with a prefix such as # to indicate single userids or a key of many authors

**Comment by RobertRR11** [comment]
Or we just keep it as it is right now, simple and clean. I see no issues.

**Comment by Juknum** [comment]
Kinda complicated & unnecessary, textures rarely go further than 4/5 contributors, which is way before the Discord limit of characters for a field (nor the whole embed)
