### ISSUE TITLE
[Feature] Allow to search through vanilla programmer art textures in `/texture`

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Discord-Bot#204]
We now have programmer art branches on the Default-Java repo for versions 1.14 and above. It would be great if it were possible to search for these just like you can already search for regular vanilla 16x textures.

**How it should work:**
`Vanilla 16x (Programmer Art)` should show up among the other projects when choosing one from the menu.
If the user selects a version ≥1.14, the PA branches are used. Otherwise, the regular ones are used (as they're already programmer art by themselves)

Note: Ideally #30 should be implemented before this feature is.

**Comment by 3vorp** [comment]
I've done a lot of research/work into how this could be done, and this would require an additional api endpoint and generally a lot of extra hassle so this is probably not happening any time soon unfortunately (unless I can somehow get the api to work)

**Comment by 3vorp** [comment]
completed with 6723f935b8a98f03a26258ca48d9e23fb4d39a94
