### ISSUE TITLE
[Feature] Add Classic Faithful 32x PA Bedrock to Autopush

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Discord-Bot#207]
### Describe the feature you'd like

Similarly to how the 32x Jappa submission channel pushes to both the Java and Bedrock repositories, please make the 32x programmer art channel do the same.

This previously was not the case since there was no 32x PA for bedrock during the initial setup, but now it has been out for a while and should definitely be connected.

The GitHub URL of the repository in question can be found at https://github.com/classicfaithful/32x-programmer-art-bedrock.

**Comment by Juknum** [comment]
Needs to be tested, but this should have been done with #209
