### ISSUE TITLE
[Bug] Autopush on the Classic Faithful server completely fails.

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Discord-Bot#208]
### What happened?

When instapassing a texture in any classic faithful submission channel, the embeds and buttons work fine, but the textures do not get pushed to any branch.

### To reproduce

1. Submit a texture to any Classic Faithful submission channel (#32x-submit-jappa, #32x-submit-progart, or #64x-submit-jappa).
2. Open the instapass/invalid menu using the gray arrow button and press instapass (the gold star icon).
3. Check the #github channel, no pushes appear. The embed colors change fine, and the buttons seem to work, but on the site and GitHub desktop no commits appear to pull.

### Notes

The workaround is to simply cherry pick any changes by hand, however 32x-programmer art has almost every branch entirely maintained through autopush, and as a result any changes made have to be manually backported to around 15 branches, which takes a very long time to do. 

The whole setup was also working entirely fine until July 23rd, so I'd suggest to look for changes made around that time period.

**Comment by 3vorp** [comment]
UPDATE: The buttons are no longer working as well, and the detection from posting an image to generating the embed is taking significantly longer (around 30 seconds to a minute rather than less than 5 seconds).

**Comment by RobertRR11** [comment]
has been fixed uhhhh sometime

**Comment by RobertRR11** [comment]
where can I close issues on mobile

**Comment by RobertRR11** [comment]
found it
