### ISSUE TITLE
[Feature] Add support for Classic Faithful 32x PA Bedrock into /texture.

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Discord-Bot#212]
### Is your feature request related to a problem?

No.

### Describe the feature you'd like

Pretty much what it sounds like, when running /texture on CF 32x PA for a bedrock exclusive texture, currently it does not show up.

This should ideally function exactly as the main Faithful packs, and Classic Faithful 32x Jappa do currently.

### Notes

Pretty high priority but not an absolute must.

**Comment by 3vorp** [comment]
Is this even planned in the future? It's been pretty much a month and it's essentially entirely halting development of a major pack, as we can't even figure out what is missing.

**Comment by Juknum** [comment]
Of course it's planned, but you might already know why it's not done yet : we aren't paid to make such a job, so we do it whenever we got time for it.

**Comment by Juknum** [comment]
Btw the project is open source, you can do it yourself

**Comment by 3vorp** [comment]
Managed to do it myself through the webapp, unnecessary to implement now.
