### ISSUE TITLE
[Feature] Add a command to check for textures not present in vanilla assets for any Faithful-related project.

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Discord-Bot#213]
### Describe the feature you'd like

Oftentimes, particularly when backporting or changing versions, certain textures that are not necessary or shouldn't be there can slip in. While there is a [tool that can already do this](https://mctools.mullak99.co.uk/textures), it would be far more convenient within the Discord client, very similar to how /missing works.

### References

https://mctools.mullak99.co.uk/textures and https://nera-w.github.io/packchecker.html already do similar, the latter one has not been updated in some time however.

### Notes

Pretty low priority overall, just a nice quality of life feature to potentially consider.

**Comment by Pomi108** [comment]
If this is added there needs to be a check so that huge_chungus isn't shown

i mean what

**Comment by 3vorp** [comment]
add it to the vanilla assets and db as well :trollface: 

~~also since when can you use non-standard emojis on github~~

**Comment by 3vorp** [comment]
done in https://github.com/Faithful-Resource-Pack/Discord-Bot/commit/0367d12b530deaaa8726eba2a0727dd78ed48cc2, including said check for huge_chungus
