### ISSUE TITLE
[Feature] Don't omit `assets/minecraft/textures` and `textures/` from paths (in various embeds)

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Discord-Bot#218]
### Is your feature request related to a problem?

We're going to support some default Forge and Fabric textures soon. These are not in the `minecraft` namespace, meaning that omitting the initial part of the path would produce misleading and incorrect results.

### Describe the feature you'd like

Title.

**Comment by Juknum** [comment]
Can you list those embeds? thx

**Comment by 3vorp** [comment]
Hasn't the same applied to OptiFine CTM for some time now though? It's generally a bit easier to sort through with `/missing` with the current setup as well.

**Comment by Pomi108** [comment]
I think this affects the embed from `/texture` only, actually

**Comment by 3vorp** [comment]
ah if it's just for `/texture` it shouldn't generally matter too much in regular use

**Comment by Juknum** [comment]
It's already the case, if the specified assets for the texture is `minecraft`, then the asset folder isn't shown, hence the asset folder is kept if it isn't `minecraft`:

https://github.com/Faithful-Resource-Pack/Discord-Bot/blob/983213d2b7099e038e8db1fa782172d4d5978a7b/src/helpers/functions/getTexture.ts#L118-L137

https://github.com/Faithful-Resource-Pack/Discord-Bot/blob/983213d2b7099e038e8db1fa782172d4d5978a7b/src/helpers/functions/getTexture.ts#L126
