### ISSUE TITLE
Use settings to configure submission process

### ISSUE THREAD

**Issue by TheRolfFR** [Faithful-Resource-Pack/Discord-Bot#227]
After a recent study of the code, it seems that some value are still hard coded inside the code:
https://github.com/Faithful-Resource-Pack/Discord-Bot/blob/249bf93b63ee85f364b109ce288c33055e9338bf/events/ready.js#L29-L39

For better flexibility and future, you should use the JSON settings and loops in order to configure all the submissions processes at once.
This could allow, for example, easier configuration for new projects and channel changes, or modify vote times

- [x] Group submission process data by project
- [x] Add Discord server and channel to project
- [x] Add vote time by project

Any suggestion or feedback is appreciated

**Comment by Juknum** [comment]
Yes its already the case, but the submission system is gonna be moved on the webapp once the api is fully rewritten

**Comment by 3vorp** [comment]
given that v3 is kinda dead and the api rewrite is gonna take some time I've gone through the liberty of removing (hopefully) all hardcoded channel ids in the submission process, and fully removing legacy f64 channel ids back when it used to have a separate server

**Comment by 3vorp** [comment]
completed with #228
