### ISSUE TITLE
[FEATURE] Recursively detect multiple files uploaded in one message for submissions

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Discord-Bot#232]
This can be accomplished in the JS bot pretty easily. Benefits include pinging people less, easier to upload multiple related textures, and saved time

It's already a feature in v3 submissions but let's be honest, nobody is gonna ever finish that at this rate
.

**Comment by Juknum** [comment]
> It's already a feature in v3 submissions but let's be honest, nobody is gonna ever finish that at this rate

Maybe it would be already over if you were focusing on helping us rather than maintaining **deprecated** stuff.

**Comment by Pomi108** [comment]
maybe it would be over if you developed the supposedly in-development TS bot

**Comment by Pomi108** [comment]
bit hard to help someone with something when no progress has been made for literal months innit

**Comment by 3vorp** [comment]
the problem is also that submissions v3 relies on the v3 API which isn't done either so there's like two projects in one that need to be done there

to put it mildly the project is kinda screwed unless someone who knows how the api even works actually takes charge and does something

I'd much rather develop with the existing working framework personally

**Comment by RobertRR11** [comment]
> v3 relies on the v3 API

where does it say that?

**Comment by RobertRR11** [comment]
> Maybe it would be already over if you were focusing on helping us rather than maintaining **deprecated** stuff.

For me it's not even possible to switch to the branch due to git errors, so you can't expect us to work on it. Also your last commit in this whole organization was in January

**Comment by 3vorp** [comment]
> > v3 relies on the v3 API
> 
> where does it say that?

<img width="560" alt="Screen Shot 2023-06-05 at 3 45 06 PM" src="https://github.com/Faithful-Resource-Pack/Discord-Bot/assets/75297863/9f8593d3-4160-4aea-b467-f86dcdd9836b">

**Comment by 3vorp** [comment]
also I plan on doing this I just wanted to make my intentions more clear here and have a place to track additional problems that occur

**Comment by 3vorp** [comment]
I didn't end up doing this recursively but everything works so honestly if it works it works
